const AllProducts = [
  {
    Id: 1,
    Title: "DJI 2212 920KV Brushless DC Motor for Drone with Black Cap",
    Rel: "motor",
    Amount: 690,
    Image: "https://robosynckits.in/wp-content/uploads/2022/05/923.jpg",
    Specifications: {
      Motor_KV: "920 RPM/V",
      MotorRotation: "CW",
      Thrust: "Around 0.5 kg",
      LiPO_Batteries: "3S-4S",
      ESC: "30 A",
      Shaft_Diameter: "6 mm",
    },
    Description:
      "This motor provides a Motor kV of 920 and gives a thrust of 500 gm. The Ready to Sky brand gained more popularity in the market due to the highest standards for optimal performance and reliability.",
    Features: [
      "Stable Performance",
      "Compact size",
      "Offers great performance and value for money",
      "Provides 0.5 kg of thrust",
    ],
    Package_Includes: [
      "1 x 2212 920KV Brushless Motor for DJI",
      "1 x Black Cap",
    ],
  },
  {
    Id: 2,
    Title: "5010 750KV High Torque Brushless Motor for Drone",
    Rel: "motor",
    Amount: 1500,
    Image: "https://robosynckits.in/wp-content/uploads/2023/12/1.jpg",
    Specifications: {
      Motor_KV: "750KV",
      LiPOBattery: "2-6s Li-Po",
      ESC: "20-40A",
      ShaftSize: "4mm",
      Propeller: "14″ – 16″ inch",
      CableLength: "40cm",
    },
    Description:
      "This 5010 750KV High Torque Brushless Motor for Drone comes with self-cooling technology, able to withstand high temperatures up to 140° C.",
    Features: [
      "Four fan-style cooling holes",
      "NdFeB magnets with a high-temperature rating",
      "140° C high temperature rated wire",
      "Epoxy-coated inner surface",
    ],
    Package_Includes: [
      "1 x 5010 750KV High Torque Brushless Motor",
      "3 x Male Female Golden Connector Pairs",
      "1 x Propeller Mount with Accessories",
    ],
  },
  {
    Id: 3,
    Title: "EMAX ECO II Series 2207 Motor (1700KV/2400KV)",
    Rel: "motor",
    Amount: 1000,
    Image:
      "https://www.quadkart.in/wp-content/uploads/2021/01/EMAX-ECO-II-Series-2306-Motor-1700KV-1900KV-2400KV-Image-1.webp",
    Specifications: {
      Brand: "Emax",
      KV: "1700KV/1900KV/2400KV (Optional)",
      Framework: "12N14P",
      Length: "33.2mm",
      Diameter: "27.5mm",
      No_of_cells: "3-6S 1700KV",
      Propeller: "5″-5.5″",
      Weight: "33.4g (Without Silicone Wire)",
    },
    Description: "NA",
    Features: [
      "Precision bearing",
      "Steel shaft",
      "Anodized finish",
      "Multi-strand winding",
    ],
    Package_Includes: [
      "1 x EMAX ECO II 2207 Motor",
      "5 x M3*8 Screws",
      "1 x Aluminum M5 Nylock Nut",
    ],
  },
  {
    Id: 4,
    Title: "Emax ES08MA II Servo",
    Rel: "motor",
    Amount: 1130,
    Image: "https://robosynckits.in/wp-content/uploads/2023/01/servo124.jpg",
    Specifications: {
      OperatingVoltage: "4.8V~6.0V",
      OperatingCurrent: "200mA/60º",
      Torque: "1.6/2.0 kgf.cm",
      OperatingSpeed: "0.12sec/60º at 4.8V; 0.10sec/60º at 6V",
    },
    Description:
      "This is an EMAX ES08MA II 12g mini metal gear analog servo. It is used in science projects, robotic equipment, and RC models.",
    Features: [
      "Ultra-thin design",
      "Super tough gear set",
      "Noble potentiometer for high accuracy",
      "Dual bearing design",
    ],
    Package_Includes: ["1 x Emax ES08MA II Servo"],
  },
  {
    Id: 6,
    Title: "EMAX ES08MD 13g Mini Metal Digital Servo For RC Model in India",
    Rel: "motor",
    Amount: 1300,
    Image: "https://robosynckits.in/wp-content/uploads/2022/02/emax122.png",
    Specifications: {
      OperatingVoltage: "4.8-6.0V DC",
      StallTorque: "1.6Kgf.cm(21.0 oz.in)",
      OperatingSpeed: "0.12 sec/60º at 4.8V, 0.10 sec/60º at 6.0V",
      Size: "23×11.5x24mm",
      Weight: "12g",
      Type: "Digital Metal Gear",
    },
    Description: "NA",
    Features: [
      "Counter Clockwise Direction",
      "Lubricated ball bearings",
      "Durable construction",
    ],
    Package_Includes: [
      "1 x ES08MD-II Servo",
      "1 x Control Horn Set",
      "1 x Screw Set",
    ],
  },
  {
    Id: 7,
    Title:
      "Emax ES3054 30 N-cm 23T Metal Gear Digital Servo ES3154 upgrade in India",
    Rel: "motor",
    Amount: 1899,
    Image: "https://robosynckits.in/wp-content/uploads/2021/05/emax30.jpg",
    Specifications: {
      OperatingVoltage: "4.8 ~ 6.0V",
      DegreeOfRotation: "180°",
      StallTorque: "30 N-cm at 4.8V",
      OperatingSpeed: "0.15 sec/60° at no load",
      Size: "28.45×13.00×31.10mm",
      Weight: "17g",
    },
    Description: "NA",
    Features: ["High Torque", "Quick Rotation", "Lightweight design"],
    Package_Includes: [],
  },
  {
    Id: 8,
    Title: "MAD 3508 IPE 2pcs/box-580KV",
    Rel: "motor",
    Amount: 8900,
    Image:
      "https://robosynckits.in/wp-content/uploads/2021/03/MAD-Motor-3508-IPE-1_1_650x500.jpg",
    Specifications: {
      Weight: "99g",
      Thrust: "2000g",
      IP_Rating: "IP35",
    },
    Description:
      "INDUSTRY PROFESSION EDITION is designed to achieve waterproof and dust proof IP35 degree of protection. High performance and low power consumption at high voltage applications.",
    Features: [
      "Water and dust resistant",
      "Oversized durable bearings",
      "Standard mounting holes",
      "High efficiency",
    ],
    Package_Includes: ["2 x MAD 3508 IPE Brushless Motor"],
  },
  {
    Id: 9,
    Title: "MG90S Metal Geared Micro Servo Motor",
    Rel: "motor",
    Amount: 250,
    Image: "https://robosynckits.in/wp-content/uploads/2020/12/servo-metal.jpg",
    Specifications: {
      Weight: "13 gm",
      OperatingVoltage: "4.8V~6.6V",
      Torque: "1.8kg-cm at 4.8V, 2.2kg-cm at 6.6V",
      Rotation: "180 Degree",
    },
    Description:
      "MG90S is a micro servo motor with metal gear, ideal for RC Airplane, Quadcopter or Robotic Arms.",
    Features: [
      "Less weight",
      "Compact size",
      "All Metal Gear",
      "Coreless Motor",
    ],
    Package_Includes: [],
  },
  {
    Id: 10,
    Title: "Servo motor For RC Planes and Helicopters SG90",
    Rel: "motor",
    Amount: 130,
    Image: "https://robosynckits.in/wp-content/uploads/2020/12/sg901.jpg",
    Specifications: {
      OperatingVoltage: "4.8V~6V",
      Speed: "0.10 sec/60deg (4.8v), 0.08sec/60deg (6v)",
      Torque: "1.6kg.cm (4.8v), 1.8kg.cm (6v)",
    },
    Description:
      "This is RC DM-SG90D 9g/0.08s/1.8kg.cm micro digital servo for RC helicopter.",
    Features: [
      "Plastic Gears",
      "High precision",
      "Long life Potentiometer",
      "180 Degree Rotation",
    ],
    Package_Includes: [],
  },
  {
    Id: 11,
    Title: "T Motor Navigator Waterproof Mn601-S-170KV- 2Pcs/Set",
    Rel: "motor",
    Amount: 23999,
    Image:
      "https://robosynckits.in/wp-content/uploads/2023/12/457_thumb_P_1501118944819.jpg",
    Specifications: {
      KV: "170KV",
      Voltage: "6-12S",
      MaxThrust: "7.5 kg",
      Weight: "60 g",
    },
    Description:
      "T Motor Mn601-S is a new generation of waterproof brushless motor. High efficiency, low consumption, and long lifespan.",
    Features: ["Waterproof", "Highly efficient", "Low consumption"],
    Package_Includes: ["2 x T Motor Navigator Mn601-S-170KV"],
  },
  {
    Id: 12,
    Title: "Hobbywing Skywalker 40A Brushless ESC",
    Rel: "motor",
    Amount: 3299,
    Image:
      "https://hitechxyz.in/cdn/shop/files/Untitleddesign_40.png?v=1721471625&width=600",
    Specifications: {
      ContinuousCurrent: "40A",
      BurstCurrent: "50A",
      BEC: "5V/3A",
      Weight: "55g",
      Size: "61x29x10mm",
    },
    Description:
      "This 40A brushless ESC from Hobbywing is designed for excellent performance in multirotor applications.",
    Features: ["Easy to use", "Strong performance", "Excellent value"],
    Package_Includes: ["1 x Hobbywing Skywalker 40A Brushless ESC"],
  },
  {
    Id: 13,
    Title: "Hobbyking 30A ESC for Electric Aircraft",
    Rel: "motor",
    Amount: 1899,
    Image:
      "https://cdn-global-hk.hobbyking.com/media/catalog/product/cache/1/image/660x415/17f82f742ffe127f42dca9de82fb58b1/legacy/catalog/30abec_1__4.jpg",
    Specifications: {
      ContinuousCurrent: "30A",
      BurstCurrent: "40A",
      BEC: "5V/3A",
      Weight: "45g",
      Size: "64 x 28 x 10mm",
    },
    Description:
      "Hobbyking 30A ESC is lightweight, reliable and has excellent performance for your electric aircraft.",
    Features: ["Lightweight design", "High efficiency", "Easy to use"],
    Package_Includes: ["1 x Hobbyking 30A ESC"],
  },
  {
    Id: 14,
    Title: "Turnigy Aerodrive 28-26 750kv Brushless Motor",
    Rel: "motor",
    Amount: 2099,
    Image:
      "https://sussex-model-centre.co.uk/cdn/shop/products/21478-main.jpg?v=1675867994&width=566",
    Specifications: {
      KV: "750KV",
      MaxCurrent: "22A",
      MaxVoltage: "12V",
      Weight: "160g",
      ShaftDiameter: "5mm",
    },
    Description:
      "The Turnigy Aerodrive 28-26 750kv Brushless Motor is a great option for multirotors, offering high efficiency and great power-to-weight ratio.",
    Features: ["High efficiency", "Powerful", "Great weight-to-power ratio"],
    Package_Includes: ["1 x Turnigy Aerodrive 28-26 750kv Brushless Motor"],
  },
  {
    Id: 15,
    Title: "2206 2300KV Brushless Motor",
    Rel: "motor",
    Amount: 1099,
    Image:
      "https://www.fabtolab.com/image/cache/data/RC/Accessories/Tornodo-2206-T2-228x228.jpg",
    Specifications: {
      KV: "2300KV",
      Max_Current: "30A",
      Weight: "29g",
      Size: "22 x 23mm",
    },
    Description:
      "2206 2300KV Brushless Motor, known for its high performance and low weight, suitable for racing drones.",
    Features: ["High efficiency", "Lightweight design", "Powerful thrust"],
    Package_Includes: ["1 x 2206 2300KV Brushless Motor"],
  },
  {
    Id: 16,
    Title: "AKK X2 Ultimate 5.8G 2000mW VTX",
    Rel: "motor",
    Amount: 5000,
    Image: "https://m.media-amazon.com/images/I/61DBjYt3iYL._AC_SX679_.jpg",
    Specifications: {
      Input_Voltage: "7-26V",
      Output_Power: "25mW, 200mW, 600mW, 1000mW, 2000mW",
      Weight: "20g",
      Size: "32x32mm",
    },
    Description:
      "The AKK X2 Ultimate is a powerful video transmitter offering five power levels, perfect for FPV racing.",
    Features: ["Compact design", "Five output power levels", "Lightweight"],
    Package_Includes: ["1 x AKK X2 Ultimate 5.8G 2000mW VTX"],
  },
  {
    Id: 17,
    Title: "HDMI to RCA Converter",
    Rel: "converter",
    Amount: 1500,
    Image:
      "https://m.media-amazon.com/images/I/31sFJCKTwCL._SX300_SY300_QL70_FMwebp_.jpg",
    Specifications: {
      Input: "HDMI",
      Output: "RCA",
      Resolution: "720p/1080p",
      Power: "USB powered",
    },
    Description: "NA",
    Features: ["Supports HD video", "Compact design", "Easy to use"],
    Package_Includes: ["1 x HDMI to RCA Converter", "1 x USB Power Cable"],
  },
  {
    Id: 18,
    Title: "USB Type-C to HDMI Adapter",
    Rel: "adapter",
    Amount: 1200,
    Image:
      "https://d2j6dbq0eux0bg.cloudfront.net/images/1107006/1118223449.jpg",
    Specifications: {
      Input: "USB Type-C",
      Output: "HDMI",
      Resolution: "4K@30Hz",
      Compatibility: "Windows/Mac",
    },
    Description: "NA",
    Features: ["4K resolution support", "Plug and play", "Lightweight"],
    Package_Includes: ["1 x USB Type-C to HDMI Adapter"],
  },
  {
    Id: 19,
    Title: "Wireless USB WiFi Adapter",
    Rel: "adapter",
    Amount: 799,
    Image: "https://robosynckits.in/wp-content/uploads/2020/12/rpi.jpg",
    Specifications: {
      Interface: "USB 2.0",
      Speed: "600 Mbps",
      Compatibility: "Windows/Linux/Mac",
    },
    Description: "NA",
    Features: ["Dual-band", "Easy installation", "Compact design"],
    Package_Includes: ["1 x Wireless USB WiFi Adapter"],
  },
  {
    Id: 20,
    Title: "Bluetooth USB Adapter",
    Rel: "adapter",
    Amount: 500,
    Image: "https://robosynckits.in/wp-content/uploads/2020/12/rpi.jpg",
    Specifications: {
      Version: "Bluetooth 5.0",
      Range: "20m",
      Interface: "USB 2.0",
    },
    Description: "NA",
    Features: ["High speed", "Wide compatibility", "Compact design"],
    Package_Includes: ["1 x Bluetooth USB Adapter"],
  },
  {
    Id: 21,
    Title: "Portable External Hard Drive 1TB",
    Rel: "storage",
    Amount: 4500,
    Image:
      "https://www.westerndigital.com/content/dam/store/en-us/assets/products/portable/wd-elements-portable/gallery/1tb/wd-elements-portable-1-2tb-front.png.wdthumb.1280.1280.webp",
    Specifications: {
      Capacity: "1TB",
      Interface: "USB 3.0",
      Size: "2.5 inches",
    },
    Description: "NA",
    Features: [
      "Compact and lightweight",
      "High speed data transfer",
      "Compatible with various devices",
    ],
    Package_Includes: ["1 x Portable External Hard Drive", "1 x USB Cable"],
  },
  {
    Id: 22,
    Title: "16GB USB Flash Drive",
    Rel: "storage",
    Amount: 299,
    Image:
      "https://rukminim2.flixcart.com/image/1200/1200/xif0q/pendrive/pendrive/f/y/o/16gb-pendrive-ultra-flair-usb-3-0-flash-drive-16gb-pendrive-original-imah2h2vhhtqnnq9.jpeg",
    Specifications: {
      Capacity: "16GB",
      Interface: "USB 2.0",
      Compatibility: "Windows/Mac/Linux",
    },
    Description: "NA",
    Features: ["Compact design", "Easy to carry", "Plug and play"],
    Package_Includes: ["1 x 16GB USB Flash Drive"],
  },
  {
    Id: 23,
    Title: "256GB SD Card",
    Rel: "storage",
    Amount: 1499,
    Image:
      "https://www.jiomart.com/images/product/original/rvh6k2kksi/sandisk-256gb-microsd-extreme-memory-edenic-product-images-orvh6k2kksi-p609974851-0-202409161822.jpg",
    Specifications: {
      Capacity: "256GB",
      Speed_Class: "UHS-I U3",
      Compatibility: "DSLR/Camera",
    },
    Description: "NA",
    Features: [
      "High speed performance",
      "Durable design",
      "Wide compatibility",
    ],
    Package_Includes: ["1 x 256GB SD Card"],
  },
  {
    Id: 24,
    Title: "Wireless Bluetooth Earbuds",
    Rel: "audio",
    Amount: 1999,
    Image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT22KGBu9uP30L8HM3yFChkEvvHUw9zEKPdV7WtitI_ocGUhrtEctqaCBPagRGub35Eu5OT2NShrG_IrrOjN7k-Pk_CwvdLsfag6YzyZ53XL_0pst2UP6Y5qNk",
    Specifications: {
      Bluetooth_Version: "5.0",
      Battery_Life: "5 hours",
      Charging_Case: "Yes",
    },
    Description: "NA",
    Features: ["Comfortable fit", "Great sound quality", "Noise cancellation"],
    Package_Includes: [
      "1 x Wireless Bluetooth Earbuds",
      "1 x Charging Case",
      "1 x USB Charging Cable",
    ],
  },
  {
    Id: 25,
    Title: "Wired Over-Ear Headphones",
    Rel: "audio",
    Amount: 999,
    Image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQG66zivZIFlwZb-32iQ4tCe5VXEAgoD7l_KQvGEDVuo8xDyV3yjs0h2IYlP85BtOVNIKVLgnRBXlBmhOAjf8ceBnEvWRQfDNaQqzlk190zVtXET0BEMn6Z",
    Specifications: {
      Driver_Size: "40mm",
      Impedance: "32 ohm",
      Cable_Length: "1.2m",
    },
    Description: "NA",
    Features: [
      "Comfortable design",
      "Great sound quality",
      "Adjustable headband",
    ],
    Package_Includes: ["1 x Wired Over-Ear Headphones"],
  },
  {
    Id: 26,
    Title: "USB Microphone",
    Rel: "audio",
    Amount: 1499,
    Image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTc74_oHqJjr9IN1m0gaZUB39PNRLZcPU02idxICkPUHiGcND2K8druYSV2ind4naz6gdja-cRA1wdP4isjWsFrQTZTj_B6u_pK3JutAjNa5xUqNFbOjycVwQ",
    Specifications: {
      Type: "Condenser",
      Frequency_Response: "20Hz-20kHz",
      Connection: "USB",
    },
    Description: "NA",
    Features: ["Clear sound quality", "Plug and play", "Compact design"],
    Package_Includes: ["1 x USB Microphone"],
  },
  {
    Id: 27,
    Title: "Gaming Mouse",
    Rel: "peripheral",
    Amount: 1299,
    Image:
      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcREHbPy4ir0A3zi9pYkwjtiubyzPl12vBNtIGByUH4psTsPs-TRmMYSAcZ6LAI_AFRV025usYi6YkGq5ZLRnhzjPMkW1u4hAjnFPcQC-CFHH3WOOWcz7h43",
    Specifications: {
      DPI: "3200",
      Connection: "USB",
      Weight: "120g",
    },
    Description: "NA",
    Features: ["High precision", "Customizable buttons", "Ergonomic design"],
    Package_Includes: ["1 x Gaming Mouse"],
  },
  {
    Id: 28,
    Title: "Mechanical Gaming Keyboard",
    Rel: "peripheral",
    Amount: 3499,
    Image:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSOsXxGYitp7VFkjyeuucEqfA7ZWYsgQy9OIe4hIURqNnfDPydjtS2X6EIEET66W4IEzrnJ6CkTNBlxF_oWc4MjiKg5qAOsq5r9KSYS1UqofBrsFO6m6Pc1LYc",
    Specifications: {
      Switch_Type: "Blue",
      Key_Roll_over: "Anti-ghosting",
      Backlight: "RGB",
    },
    Description: "NA",
    Features: [
      "Customizable RGB lighting",
      "Durable construction",
      "Great tactile feedback",
    ],
    Package_Includes: ["1 x Mechanical Gaming Keyboard"],
  },
  {
    Id: 29,
    Title: "Webcam 1080p HD",
    Rel: "peripheral",
    Amount: 2499,
    Image:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRore0YZsPVIlr-qwbrNEBGAMQfHjTHpz_VzDFRwx9nDSgfoqBqyO4u_VnC4Gtmnnli8xVXiKrgTMYE36RsLh6g55eOXED5ei5ZZFWd-xN1F5Z2O7uo37Up",
    Specifications: {
      Resolution: "1080p",
      Field_of_View: "90 degrees",
      Connection: "USB",
    },
    Description: "NA",
    Features: ["High-definition video", "Built-in microphone", "Plug and play"],
    Package_Includes: ["1 x Webcam"],
  },
  {
    Id: 30,
    Title: "HDMI Switch 3 Port",
    Rel: "switch",
    Amount: 999,
    Image: "https://m.media-amazon.com/images/I/51LYsmN-JUL.jpg",
    Specifications: {
      Input_Ports: "3",
      Output_Port: "1",
      Support: "4K@60Hz",
    },
    Description: "NA",
    Features: [
      "Easy switching between devices",
      "Compact design",
      "Supports 4K resolution",
    ],
    Package_Includes: ["1 x HDMI Switch", "1 x USB Power Cable"],
  },
];

export default AllProducts;
